# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OVKrrUdoMvQTff5IJYgk-tBTSm48r9gL
"""

from .object_detection import detect_common_objects